server:
  port: 8081
spring:
  application:
    name: backend-config-server
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/Leonardo976/Tingeso-2
          search-paths: "config-data"