apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-archivos-deployment
  labels:
    app: backend-archivos-deployment
spec:
  selector:
    matchLabels:
      app: backend-archivos-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-archivos-deployment
    spec:
      containers:
        - name: topeducation-cuotas-postgres
          image: benjamingonzalezh/topeducation-archivos-postgres:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://backend-config-server:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://backend-eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_ARCHIVOS
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_ARCHIVOS
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend-archivos-service
  labels:
    app: backend-archivos-service
spec:
  selector:
    app: backend-archivos-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer